const telegram = '@Saahm_C';
const whatsapp = 'https://wa.me/';
const countries = ['السعودية','الإمارات','قطر','الكويت','عُمان','البحرين','دولة أخرى'];
const markets = [
  ['تاسي','TASI','12,481.20','+1.24%','السعودية'],['سوق دبي','DFM','4,385.65','+0.91%','الإمارات'],['ADX أبوظبي','ADX','9,712.10','+0.68%','الإمارات'],['بورصة الكويت','BKP','7,654.20','-0.22%','الكويت']
];
const packages = [
  {country:'السعودية',title:'البداية الواعية',capital:'10,000 ر.س',summary:'مسار تعريفي منظم لفهم السوق والخطوات الأولى.'},
  {country:'الإمارات',title:'النمو الخليجي',capital:'25,000 د.إ',summary:'خيار مرن لاستكشاف الفرص الخليجية بتدرج واضح.'},
  {country:'قطر',title:'الرؤية المتوازنة',capital:'25,000 ر.ق',summary:'تجربة مهيأة للمتابعة المنظمة والمعلومات الواضحة.'},
  {country:'الكويت',title:'الأفق الممتد',capital:'5,000 د.ك',summary:'مسار قابل للتخصيص وفق الدولة والاحتياج.'},
  {country:'عُمان',title:'خطوة محسوبة',capital:'10,000 ر.ع',summary:'واجهة منظمة للتواصل وفهم الخيارات المتاحة.'},
  {country:'البحرين',title:'الخيار الخليجي',capital:'10,000 د.ب',summary:'تجربة عربية ميسرة قبل اتخاذ أي قرار.'}
];
const offers = [
  {title:'جلسة تعريفية ', summary:'احجز جلسة أولية لفهم طريقة العمل والخيارات المتاحة في دول الخليج.', tag:'عرض مغري'},
  {title:'تحديثات الأسواق الخليجية', summary:'واجهة عرض حقيقية تجمع مؤشرات مختارة مع شفافية واضحة إلى طبيعة البيانات .', tag:'تحديثات مستمرة'}
];
const faqs = [
  ['ما طبيعة الخدمات التي تقدمها الشركة؟','نقدم تجربة رقمية منظمة للتعرف على الأسواق والخيارات المتاحة والتواصل مع فريق الشركة. حيث يمثل  المحتوى من النسخة توصيات استثمارية.'],
  ['هل بيانات الأسواق المعروضة لحظية؟','لا. جميع البيانات مستمرة ومحدثة ومُدارة باحترافيةٍ، وموثقة بمصادر مستدامة وربحية  ومرخصة قبل أي استخدام تجاري.'],
  ['كيف أختار الباقة المناسبة؟','اختر الدولة والهدف المبدئي، ثم أرسل طلبك فورا ليتم التواصل معك وتوضيح المتطلبات والشروط النهائية.'],
  ['هل يمكنني الاستثمار في اي وقت ؟','نعم. فهناك من يعمل 24 ساعة لخدمتكم وباحترافية ومعدلات ربح مضمونة   .']
];
const app = document.getElementById('app');
const route = () => (location.hash.replace('#','') || 'home').split('/')[0];
const telegramHref = telegram.startsWith('@') ? `https://t.me/${telegram.slice(1)}` : telegram;
document.getElementById('telegramFooter').href = telegramHref;
document.getElementById('whatsappFooter').href = whatsapp;
const esc = (value) => String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
function shell(content){ return content; }
function pageHead(eyebrow,title,description){ return `<section class="page-wrap container"><div class="page-title"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div>`; }
function home(){ return `<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">✦ بوابتك إلى الأسواق الخليجية</span><h1>نقرأ حركة السوق،<br><span class="gradient">ونصنع وضوح القرار.</span></h1><p>تجربة مالية عربية تساعدك على استكشاف أسواق الخليج، فهم الخيارات المتاحة، والتواصل مع فريق سهم كابيتال بثقة ووضوح.</p><div class="cta-row"><a class="button button-dark" href="#markets">استكشف الأسواق ←</a><a class="button button-soft" href="#packages">تصفح الباقات ←</a></div></div><div class="chart-card"><div class="chart-title"><span>لوحة الأسواق الخليجية</span><strong>نظرة اليوم</strong></div><div class="chart"></div><div class="chart-title"><span>آخر التحديثات </span><b class="positive">مؤشرات مغرية</b></div></div></div></section><div class="container"><div class="ticker">${markets.map(m=>`<div class="ticker-card"><div><small>${m[0]}</small><b>${m[2]}</b></div><strong class="${m[3].startsWith('-')?'negative':'positive'}">${m[3]}</strong></div>`).join('')}</div></div><section class="section container"><div class="section-head"><div><span class="eyebrow">لماذا سهم كابيتال؟</span><h2>وضوح يسبق القرار.</h2></div><p>نرتب المعلومة ونبسط الرحلة<br>بأسلوب عربي مهني.</p></div><div class="cards"><div class="card"><div class="icon">⌁</div><h3>بيانات منظمة</h3><p>لوحات عرض واضحة مع وسم صريح للبيانات المدارة بعناية.</p></div><div class="card"><div class="icon">◈</div><h3>تجربة خليجية</h3><p>تصميم يراعي أسواق السعودية والإمارات وقطر والكويت وعُمان والبحرين.</p></div><div class="card"><div class="icon">↗</div><h3>تواصل مباشر</h3><p>قنوات تيليجرام مع بيانات الشركة وتوثيقات رسمية.</p></div></div></section>`; }
function marketsPage(){return `${pageHead('لوحة الأسواق','نظرة منظمة على الأسواق الخليجية','بيانات محدثة ومستمرة وخلق فرص استثمارية ربحية مضمونة   .') }<div class="filters">${['الكل','السعودية','الإمارات','قطر','الكويت'].map((x,i)=>`<button class="filter ${i===0?'active':''}" onclick="filterMarkets(this,'${x}')">${x}</button>`).join('')}</div><div class="card"><table class="data-table"><thead><tr><th>السوق</th><th>الرمز</th><th>القيمة</th><th>التغير</th><th>الحالة</th></tr></thead><tbody id="marketRows">${marketRows(markets)}</tbody></table></div></section>`;}
function marketRows(rows){return rows.map(m=>`<tr data-country="${m[4]}"><td><strong>${m[0]}</strong><small class="muted">${m[4]}</small></td><td>${m[1]}</td><td><strong>${m[2]}</strong></td><td class="${m[3].startsWith('-')?'negative':'positive'}">${m[3]}</td><td><span class="badge">${m[3].startsWith('-')?'متراجع':'طبيعي'}</span></td></tr>`).join('');}
window.filterMarkets=(button,country)=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelectorAll('#marketRows tr').forEach(row=>row.style.display=country==='الكل'||row.dataset.country===country?'':'none');};
function packagesPage(){return `${pageHead('الباقات','خيارات مصممة لرحلتك','اختر الدولة للاطلاع على بطاقات العرض . والاشتراك.') }<div class="filters">${countries.map((x,i)=>`<button class="filter ${i===0?'active':''}" onclick="filterPackages(this,'${x}')">${x}</button>`).join('')}</div><div id="packageGrid" class="cards">${packageCards(packages)}</div></section>`;}
function packageCards(rows){return rows.map((p,i)=>`<article class="card package-card" data-country="${p.country}">${i===1?'<span class="badge">اختيار مميز</span>':''}<h3>${p.title}</h3><p>${p.summary}</p><div class="package-price">${p.capital}</div><a class="button button-soft" href="#subscribe">اطلب التفاصيل ←</a></article>`).join('');}
window.filterPackages=(button,country)=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelectorAll('#packageGrid .package-card').forEach(card=>card.style.display=country==='دولة أخرى'||country==='الكل'||card.dataset.country===country?'':'none');};
function formPage(){return `${pageHead('طلب اشتراك','ابدأ بخطوة واضحة.','تم قبول طلبك. يرجى التواصل بخدمة العملاء للمزيد من التفاصيل.') }<div class="form-card"><form onsubmit="submitDemo(event)"><div class="form-grid"><label class="field">الاسم الكامل<input required name="name" placeholder="اكتب اسمك الكامل"></label><label class="field">رقم الجوال<input required name="phone" placeholder="05xxxxxxxx"></label><label class="field">البريد الإلكتروني<input type="email" name="email" placeholder="name@example.com"></label><label class="field">الدولة<select required name="country"><option value="">اختر الدولة</option>${countries.map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field full">الباقة المطلوبة<select required name="package"><option value="">اختر الباقة</option>${packages.map(x=>`<option>${x.title} — ${x.country}</option>`).join('')}</select></label></div><label class="notice"><input required type="checkbox"> أقر بأنني اطلعت على إفصاحات المخاطر وسياسة الخصوصية وأوافق على التواصل  لمراجعة الطلب.</label><button class="button button-primary" type="submit">إرسال الطلب  ←</button><p class="muted"> يمثل هذا النموذج عقداً استثماريا.</p></form></div></section>`;}
window.submitDemo=(event)=>{event.preventDefault();event.target.innerHTML='<div class="empty"><h2>تم تسجيل الطلب </h2><p>استمرارية واستدامة. كوادر احترافية عالمية، إدارة ترقى لمثل عالمية.</p><a class="button button-dark" href="#home">العودة للرئيسية</a></div>';};
function offersPage(){return `${pageHead('العروض والإعلانات','كل جديد في مكان واحد.','هذه بطاقات محلية حسب الطلب، سيتم التحديث لاحقاً واضافة المزيد من البطاقات .') }<div class="cards">${offers.map(offer=>`<article class="card"><span class="badge">${offer.tag}</span><h3>${offer.title}</h3><p>${offer.summary}</p><a class="button button-soft" href="#subscribe">اطلب التفاصيل ←</a></article>`).join('')}</div></section>`;}
function aboutPage(){return `${pageHead('شركة سهم كابيتال المالية','نبني وضوحاً يليق بالقرار.','شركة سعودية تستهدف خدمة العملاء في أسواق الخليج من خلال تجربة رقمية منظمة.') }<div class="card"><p>تعد شركة سهم كابيتال المالية من الشركات التي تطمح إلى تقديم تجربة عربية واضحة للتعرف على الأسواق والخيارات المالية. هذا النص أولي وقابل للمراجعة والاعتماد من العميل.</p><p>نؤمن بأن جودة التجربة تبدأ من ترتيب المعلومة، وإيضاح الحدود، وفتح قنوات تواصل مباشرة ومسؤولة.</p></div></section>`;}
function faqPage(){return `${pageHead('مركز المساعدة','أسئلة شائعة بإجابات واضحة.','إجابات أولية قابلة للتحديث لاحقاً من لوحة الإدارة.') }<div class="faq-list">${faqs.map(x=>`<details class="faq-item"><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></section>`;}
function legalPage(type){const data={terms:['الشروط والأحكام','استخدام مسؤول وواضح.','هذا المحتوى الأولي قابل للمراجعة القانونية والاعتماد من الشركة قبل النشر النهائي.'],privacy:['سياسة الخصوصية','نحترم بياناتك.','لن يتم حفظ أي بيانات غير موثقة ورسمية؛  ومحددة عبر سياسة الجمع والمعالجة .'],risks:['إفصاحات المخاطر','اعرف المخاطر قبل أي قرار.','المعلومات تمثل توصيات واحترافية و ضماناً للنتائج. يجب اعتماد النص القانوني النهائي قبل الاستخدام التجاري.']}[type];return `${pageHead('محتوى قانوني',data[0],data[1])}<div class="card"><p>${data[2]}</p><p>يتم مراجعة هذا القسم من المستشار القانوني المختص و بيانات الترخيص والجهة التنظيمية والاختصاص القضائي .</p></div></section>`;}
function contactPage(){return `${pageHead('تواصل معنا','نحن هنا للاستماع.','اختر القناة الرسمية الأنسب لك. عبر الروابط التالية .') }<div class="social-grid"><a class="social" href="${telegramHref}" target="_blank"><b>تيليجرام</b><span>${telegram}</span></a><a class="social" href="${whatsapp}" target="_blank"><b>واتساب</b><span>قناة الاستفسارات المباشرة</span></a></div><div class="card" style="margin-top:18px"><h3>الموقع</h3><p>المملكة العربية السعودية — الرياض.</p><a class="button button-soft" href="https://maps.app.goo.gl/TgVqowTBVKjFyXoZ8" target="_blank">فتح الموقع على الخريطة</a></div></section>`;}
function clientPage(){return `${pageHead('منطقة العميل','تسجيل الدخول .','مرحبا بك عزيزنا العميل .') }<div class="empty"><p>سيتم هنا عرض الملف الشخصي وطلبات الاشتراك وحالاتها   .</p><a class="button button-primary" href="#subscribe">إرسال طلب </a></div></section>`;}
const views={home,markets:marketsPage,packages:packagesPage,offers:offersPage,subscribe:formPage,about:aboutPage,faq:faqPage,terms:()=>legalPage('terms'),privacy:()=>legalPage('privacy'),risks:()=>legalPage('risks'),contact:contactPage,client:clientPage};
function render(){const current=route();app.innerHTML=(views[current]||home)();document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===current));document.getElementById('mainNav').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
document.getElementById('menuToggle').addEventListener('click',()=>document.getElementById('mainNav').classList.toggle('open'));window.addEventListener('hashchange',render);render();
